version: '2'
services:
  cowrie:
    image: 'cowrie/cowrie:latest'
    container_name: cowrie
    stdin_open: true
    tty: true
    ports:
      - '22:2222'
    networks:
      network_0: {}
  attacker:
    image: 'ubuntu:latest'
    container_name: attacker
    stdin_open: true
    tty: true
    networks:
      network_0: {}
networks:
  network_0:
    ipam:
      config:
        - subnet: 192.168.1.0/24
